### ISSUE TITLE
mac link error

### ISSUE THREAD

**Issue by tovasLuo** [hluk/qxtglobalshortcut#1]
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Carbon.framework/Carbon', needed by `libqxtglobalshortcut.0.0.1.dylib'.  Stop.
make[1]: *** [CMakeFiles/qxtglobalshortcut.dir/all] Error 2
make: *** [all] Error 2

**Comment by tovasLuo** [comment]
set(MAC_LIBS)

FIND_LIBRARY( CARBON_LIBRARY Carbon )
LIST( APPEND MAC_LIBS ${CARBON_LIBRARY} )

FIND_LIBRARY( COCOA_LIBRARY Cocoa )
LIST( APPEND MAC_LIBS ${COCOA_LIBRARY} )

TARGET_LINK_LIBRARIES(${bin} ${MAC_LIBS})

it works!!!

**Comment by hluk** [comment]
Can you create pull request?

**Comment by hluk** [comment]
Thanks for the PR.
