### ISSUE TITLE
missing fedora multilib support

### ISSUE THREAD

**Issue by martinkg** [hluk/qxtglobalshortcut#3]
I am missing the multilib support.
please could you add the following patch.
[qxtglobalshortcut-libdir.patch.txt](https://github.com/hluk/qxtglobalshortcut/files/1401406/qxtglobalshortcut-libdir.patch.txt)

**Comment by hluk** [comment]
Looks good, I can apply the patch, but I would prefer if you create a pull request instead. Is that possible?

**Comment by martinkg** [comment]
new patch commited, please check.
